parserOptions:
  ecmaVersion: 6
  sourceType: "module"

env:
  es6: true
  browser: true

extends: "standard"
rules:
  no-multi-spaces: "off"
  key-spacing: "off"
  brace-style:
    - "error"
    - "stroustrup"
    - allowSingleLine: true
